In [5]:
import pandas as pd
import json
import requests as rq

In [39]:
from pandas.io.json import json_normalize

In [6]:
url = 'https://app.checkbits.com.br/open_api/v1/done_forms?page=1&items=100&sort=asc&order_by=done_at&start_date=2024-01-01&end_date=2024-01-30&date_column=created_at'

In [44]:
y = rq.get("https://app.checkbits.com.br/open_api/v1/done_forms?page=1&items=100&sort=asc&order_by=done_at&start_date=2024-01-01&end_date=2024-01-30&date_column=created_at&token=Bearer%20agmP1LQMqp_c04b88e23b627afba615f4b4")
a = json.loads(y.content)

In [ ]:
a[0]['done_items'][0]['kind']

In [56]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [57]:
df = pd.DataFrame(a)

In [37]:
df.location

0    {'latitude': None, 'longitude': None, 'full_ad...
1    {'latitude': None, 'longitude': None, 'full_ad...
2    {'latitude': None, 'longitude': None, 'full_ad...
3    {'latitude': '-19.837442', 'longitude': '-40.0...
4    {'latitude': '-19.842115', 'longitude': '-40.0...
5    {'latitude': '-19.841192', 'longitude': '-40.0...
Name: location, dtype: object

In [41]:
df2 = json_normalize(df.location)

<ipython-input-41-0fa300df111a>:1: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  df2 = json_normalize(df.location)

In [45]:
df2

     latitude   longitude                 full_address
0        None        None                         None
1        None        None                         None
2        None        None                         None
3  -19.837442  -40.081158  5W79+2G Aracruz, ES, Brasil
4  -19.842115   -40.07991  5W5C+52 Aracruz, ES, Brasil
5  -19.841192   -40.07927  5W5C+G7 Aracruz, ES, Brasil

In [42]:
df.shape

(6, 14)

In [53]:
pd.concat([df,df2],axis=1)

,name,title,id,form_id,user_id,user_name,state,score,location,department_id,done_at,created_at,updated_at,done_items,latitude,longitude,full_address
0,18.1 - Tendência Financeira,None,292234,11717,6092,Alberto Kuentzer,concluded,100.0,"{'latitude': None, 'longitude': None, 'full_ad...",5970,2024-01-05T08:22:27.329-03:00,2024-01-04T13:04:02.441-03:00,2024-01-05T08:22:27.673-03:00,"[{'id': 5200005, 'title': 'Assuntos/áreas:', '...",None,None,None
1,Jaade,None,292794,13490,7307,Jaade Bomfim,concluded,100.0,"{'latitude': None, 'longitude': None, 'full_ad...",7538,2024-01-05T09:02:00.886-03:00,2024-01-05T09:01:47.954-03:00,2024-01-05T09:01:51.378-03:00,"[{'id': 5210058, 'title': 'Checklist teste', '...",None,None,None
2,8 - Checklist Acompanhamento Fluxo de Aprovaçã...,None,295074,12127,7271,Luana de Lima,concluded,100.0,"{'latitude': None, 'longitude': None, 'full_ad...",5970,2024-01-08T17:10:16.986-03:00,2024-01-08T17:09:13.067-03:00,2024-01-08T17:10:17.784-03:00,"[{'id': 5245182, 'title': 'Assuntos/áreas:', '...",None,None,None
3,ENGAXETAMENTO,None,295974,13279,7424,FELIPE BRUNO DOS REIS,concluded,100.0,"{'latitude': '-19.837442', 'longitude': '-40.0...",7488,2024-01-09T18:29:08.851-03:00,2024-01-09T18:29:13.059-03:00,2024-01-09T18:56:15.750-03:00,"[{'id': 5260663, 'title': 'Dados do Executante...",-19.837442,-40.081158,"5W79+2G Aracruz, ES, Brasil"
4,VV.CTRL.PNM_01,None,296495,13345,7416,CLEILSON DA SILVA REIS,concluded,100.0,"{'latitude': '-19.842115', 'longitude': '-40.0...",7530,2024-01-10T12:39:47.157-03:00,2024-01-10T12:39:53.974-03:00,2024-01-10T12:51:13.413-03:00,"[{'id': 5270338, 'title': 'Dados do Executante...",-19.842115,-40.07991,"5W5C+52 Aracruz, ES, Brasil"
5,VV.CTRL.PNM_01,None,296511,13345,7416,CLEILSON DA SILVA REIS,concluded,100.0,"{'latitude': '-19.841192', 'longitude': '-40.0...",7530,2024-01-10T12:49:34.073-03:00,2024-01-10T12:49:47.918-03:00,2024-01-10T12:53:24.881-03:00,"[{'id': 5270512, 'title': 'Dados do Executante...",-19.841192,-40.07927,"5W5C+G7 Aracruz, ES, Brasil"

In [69]:
df_0 = []
for i in df.done_items:
    if type(i) == list:
        for j in i:
            df_0.append(j)

In [76]:
df

,name,title,id,form_id,user_id,user_name,state,score,location,department_id,done_at,created_at,updated_at,done_items
0,18.1 - Tendência Financeira,None,292234,11717,6092,Alberto Kuentzer,concluded,100.0,"{'latitude': None, 'longitude': None, 'full_ad...",5970,2024-01-05T08:22:27.329-03:00,2024-01-04T13:04:02.441-03:00,2024-01-05T08:22:27.673-03:00,"[{'id': 5200005, 'title': 'Assuntos/áreas:', '..."
1,Jaade,None,292794,13490,7307,Jaade Bomfim,concluded,100.0,"{'latitude': None, 'longitude': None, 'full_ad...",7538,2024-01-05T09:02:00.886-03:00,2024-01-05T09:01:47.954-03:00,2024-01-05T09:01:51.378-03:00,"[{'id': 5210058, 'title': 'Checklist teste', '..."
2,8 - Checklist Acompanhamento Fluxo de Aprovaçã...,None,295074,12127,7271,Luana de Lima,concluded,100.0,"{'latitude': None, 'longitude': None, 'full_ad...",5970,2024-01-08T17:10:16.986-03:00,2024-01-08T17:09:13.067-03:00,2024-01-08T17:10:17.784-03:00,"[{'id': 5245182, 'title': 'Assuntos/áreas:', '..."
3,ENGAXETAMENTO,None,295974,13279,7424,FELIPE BRUNO DOS REIS,concluded,100.0,"{'latitude': '-19.837442', 'longitude': '-40.0...",7488,2024-01-09T18:29:08.851-03:00,2024-01-09T18:29:13.059-03:00,2024-01-09T18:56:15.750-03:00,"[{'id': 5260663, 'title': 'Dados do Executante..."
4,VV.CTRL.PNM_01,None,296495,13345,7416,CLEILSON DA SILVA REIS,concluded,100.0,"{'latitude': '-19.842115', 'longitude': '-40.0...",7530,2024-01-10T12:39:47.157-03:00,2024-01-10T12:39:53.974-03:00,2024-01-10T12:51:13.413-03:00,"[{'id': 5270338, 'title': 'Dados do Executante..."
5,VV.CTRL.PNM_01,None,296511,13345,7416,CLEILSON DA SILVA REIS,concluded,100.0,"{'latitude': '-19.841192', 'longitude': '-40.0...",7530,2024-01-10T12:49:34.073-03:00,2024-01-10T12:49:47.918-03:00,2024-01-10T12:53:24.881-03:00,"[{'id': 5270512, 'title': 'Dados do Executante..."

In [78]:
pd.DataFrame(df_0).shape

(105, 11)

In [73]:
pd.DataFrame(df_0[1:15])

,id,title,sentence,answer,kind,comment,minimum,maximum,weight,not_applied,succeeded
0,5200006,OBS:,REALIZAR O REPLAN FINANCEIRO DO PORTFÓLIO DE P...,sim,options,None,None,None,0.0,False,True
1,5200007,1.,Atualizado bases financeiras dos arquivos de T...,Sim,options,None,None,None,0.0,False,True
2,5200008,2.,Atualizado informações vindas do PPM?,Sim,options,None,None,None,0.0,False,True
3,5200009,3.,Atualizado o realizado mensal e replanejado os...,Sim,options,None,None,None,0.0,False,True
4,5200010,4.,Atualizado valores futuros ?,Sim,options,None,None,None,0.0,False,True
5,5200011,5.,Verificado a consistência das informações e va...,Sim,options,None,None,None,0.0,False,True
6,5200012,6.,Realizada as justificativas para os desvios fi...,Sim,options,None,None,None,0.0,False,True
7,5200013,7.,Atualizado a Tendência Financeira CP?,Sim,options,None,None,None,0.0,False,True
8,5200014,8.,Linhas e colunas resumo possuem fórmulas? (exc...,Sim,options,None,None,None,0.0,False,True
9,5200015,9.,Analisado o PJ de forma completa? (não só o PA...,Sim,options,None,None,None,0.0,False,True
10,5200016,10.,Verificado existência de PJs com Tend de ZFEL ...,Sim,options,None,None,None,0.0,False,True
11,5200017,11.,"Se solicitado ajuste pela Braskem, após atuali...",Sim,options,None,None,None,0.0,False,True
12,5200018,12.,Verificado se a coluna Pluri Tend e a Tend de ...,Sim,options,None,None,None,0.0,False,True
13,5200019,13.,Verificado se os Engenheiros e Coordenadores e...,Sim,options,None,None,None,0.0,False,True

In [59]:
df_0

,id,title,sentence,answer,kind,comment,minimum,maximum,weight,not_applied,succeeded
0,5200005,Assuntos/áreas:,.,Portfólio,options,None,None,None,1.0,False,True
1,5200006,OBS:,REALIZAR O REPLAN FINANCEIRO DO PORTFÓLIO DE P...,sim,options,None,None,None,0.0,False,True
2,5200007,1.,Atualizado bases financeiras dos arquivos de T...,Sim,options,None,None,None,0.0,False,True
3,5200008,2.,Atualizado informações vindas do PPM?,Sim,options,None,None,None,0.0,False,True
4,5200009,3.,Atualizado o realizado mensal e replanejado os...,Sim,options,None,None,None,0.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...
19,5270531,Caso a VÁLVULA tenha sido removida o flange fo...,.,5,thumb,None,None,None,0.0,False,True
20,5270532,"Local de trabalho foi entregue organizado, lim...",.,5,thumb,None,None,None,0.0,False,True
21,5270533,LT - O documento foi encerrado pela operação?,.,5,thumb,None,None,None,0.0,False,True
22,5270534,TAG - O equipamento foi desbloqueado?,.,5,thumb,None,None,None,0.0,False,True
23,5270535,A manutenção foi realizada conforme instrução ...,.,5,thumb,None,None,None,0.0,False,True